config/routes.rb
Gobblr::Application.routes.draw do
  root 'welcome#index'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/auth/:provider/callback'  => 'sessions#create' 
  get '/users/:id'                => 'users#show', as: :home
  post '/users/:id'               => 'feeds#create', as: :feeds
  get '/logout'                   => 'sessions#destroy', as: :logout
  get 'feeds/twitter_create'      => 'feeds#add_home_twitter_feed', as: :twitter_feed_create
  post '/posts/:id/favorite'      => "posts#fave", as: :favorite
  post '/posts/:id/unfavorite'    => "posts#unfave", as: :unfavorite
  post '/posts/:id/retweet'       => "posts#retweet", as: :retweet

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :feed_users
  has_many :feeds, through: :feed_users
  has_many :posts, through: :feeds
  has_many :authorizations
  validates :username, :secret, :token, presence: true

  def self.find_or_create_from_omniauth(auth_hash)
    @user = User.find_by(username: auth_hash['info']['name'])
    @user.update(token: auth_hash['credentials']['token'])
    @user.update(secret: auth_hash['credentials']['secret'])
  end

  def self.create_from_omniauth(auth_hash)
    self.create!(   
    username: auth_hash['info']['name'],
    token:    auth_hash['credentials']['token'],
    secret:   auth_hash['credentials']['secret']
    )
    rescue ActiveRecord::RecordInvalid
      nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @search = Post.search_bar(params[:search_params],
                              params[:search_type],
                              @current_user.token,
                              @current_user.secret,
                              @current_user.username)
    @feed = Feed.new
    @posts = @current_user.posts.order('published DESC').paginate(page: params[:page])
    if @search != nil
      if (@search[:feed] == 0 || @search[:feed] == 404)
        flash.now[:notice] = 'Invalid feed URL. Please try again.'
        flash.now[:feed_notice] = 'Invalid feed URL. Please try again.'
        @search[:feed] = 0
      end
      if @search[:tumblr] == 0
        flash.now[:notice] = 'No tumblr match found.'
        flash.now[:tumblr_notice] = 'No tumblr match found.'
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_posts.html.erb
<div class = 'apple_pagination'>
<%= will_paginate @posts %>
</div>
<% @posts.each do |post| %>
    <div class="<%= post.feed.type.downcase %>" >
    <% if post.url && post.title %>
      <%= link_to post.title, post.url %><br>
    <% else %>
      <%= post.title %>
    <% end %>
    <% if post.aurl %>
      <img src='<%= post.aurl %>'>
    <% end %><br>
    <%= post.artist if post.artist %><br>
  by <%= post.author %><br><br>
  <%= post.published.to_time %><br>
  <a href="<%= post.url %>">
  <% if post.content_type == 'photo' %>
    <% post.content.split.each do |photo| %>
      <img src='<%= photo %>' >
    <% end %>
  <% elsif post.content_type != 'photo' %>
    <%= post.summary.html_safe if post.summary %><br>
    <%= post.content.html_safe if post.content %><br><br>
  <% end %>
  <% if post.quote_source %>
   - <%= post.quote_source.html_safe %>
   <% end %>
    <%= post.embed.html_safe if post.embed %>
  </a>
    <% if post.feed.type == "TwitterFeed" && !post.its_a_fave(current_user) %>
      <%= button_to "Favorite", favorite_path(post.id) %>
    <% elsif post.feed.type == "TwitterFeed" %>
      <%= button_to "Unfavorite", unfavorite_path(post.id) %>
    <% end %><br>
    <% if post.feed.type == "TwitterFeed" && !post.is_it_retweeted(current_user) %>
      <%= button_to "Retweet", retweet_path(post.id) %>
    <% end %>
    <!-- Tweet Button Logic, Button and Javascript-->
    <% if post.title %>
      <% twitter_text = post.title %>
      <% author = "" %>
      <% url = post.url %>
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= url %>" data-via="<%= author %>" data-text="<%= twitter_text %>" data-dnt="true" data-count="none">Tweet</a>
    <% elsif post.feed.type == "TwitterFeed" %>
      <% twitter_text = "\""+post.content+"\"" %>
      <% author = post.author %>
      <% tweet_id = post.tweet_id %>
      <p><a href="https://twitter.com/intent/tweet?in_reply_to=<%= tweet_id %>">Reply on Twitter</a></p>
    
    <% else %>
      <% twitter_text = "Check out what I found with Gobblr!"%>
      <% url = post.url %>
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= url %>" data-via="<%= author %>" data-text="<%= twitter_text %>" data-dnt="true" data-count="none">Tweet</a>
    <% end %>
    
  <!-- End Tweet Button Logic, Button and Javascript -->
  </div>
<br>
<br>
<br>
<% end %>
<% if @posts.count == 0 %>
  <h3>Search for users to grow your feed!<h3>
<% end %>

app/views/users/_rssfeedsearch.html.erb
<h3><%= @search[:feed].title %> </h3><br>
<%= @search[:feed].description %><br>
<%= form_for @feed do |f| %>
  <%= f.hidden_field :identifier, value: params[:search_params] %>
  <%= f.hidden_field :type, value: 'Feeder' %>
  <%= f.submit "Add #{@search[:feed].title} to your feed" %>
<% end %>

app/views/users/_tumblrsearch.html.erb
<img src="<%= @search[:tumblr][:avatar] %>"><br>
Title: <%= link_to @search[:tumblr][:title], @search[:tumblr][:url], target: :blank %><br>
Author: <%= @search[:tumblr][:author] %><br>
Post Count: <%= @search[:tumblr][:post_count]%></br>
Description: <%= @search[:tumblr][:description].html_safe %></br> 
<br>
<%= form_for @feed do |f| %>
  <%= f.hidden_field :identifier, value: params[:search_params] %>
  <%= f.hidden_field :type, value: 'Tumblr' %>
  <%= f.submit "Add #{params[:search_params]} to your feed" %>
<% end %>

app/views/users/_twittersearch.html.erb
<% @search[:twitter].each do |potential_feed| %>
  <img src="<%= potential_feed.profile_image_url %>" alt="<%= potential_feed.username %>">
  <%= "@"+ potential_feed.username %>
  <%= form_for @feed do |f| %>
    <%= f.hidden_field :identifier, value: potential_feed.username %>
    <%= f.hidden_field :type, value: 'TwitterFeed' %>
    <%= f.submit "Add #{potential_feed.username} to your feed" %>
  <% end %>
<br>
<% end %>

app/views/users/show.html.erb
<div class='home'>
<span class='row'>
<h1>
  <span class='col-med-5'> <%= @current_user.username.upcase %> IS HUNGRY.</span> </h1>
</span>

<div class='row'>
  <div class='col-sm-3 sidebar'>

    <%= form_tag(home_path(@current_user.id), method: :get) do %>
      <select name="search_type">
        <option value='all'>Search All</option>
        <option value='feed'>Search Feeds</option>
        <option value='tumblr'>Search Tumblr</option>
        <option value='twitter'>Search Twitter</option>
      </select>
      <%= text_field_tag :search_params, params[:search_params], class:'form-control', placeholder: 'Search' %>
      <%= submit_tag "Go", :name =>'search by name', class: "btn btn-sml" %>
    <% end %>
    <br>
    <a href="https://twitter.com/share" class="twitter-share-button" data-text="Hello" data-dnt="true" data-count="none">Tweet</a>
    <br>
    <% @current_user.authorizations.each do |authorizations| %>
      <%= authorizations.provider %><br>
      <%= image_tag(authorizations.avatar) %><br>
      <%= authorizations.nickname %><br>
    <% end %>
  </div>
  <div class='col-sm-9'>
  <div id="search_results">
    <% unless params[:search_type] == 'all' %>
      <%= flash[:notice] %><br><br>
    <% end %>
    <% if params[:search_type] == 'twitter' %>
      <%= render 'twittersearch' %>
    <% elsif params[:search_type] == 'feed' && @search[:feed] != 0 && @search[:feed] != 200 %>
      <%= render 'rssfeedsearch' %>
    <% elsif params[:search_type] == 'tumblr' && @search[:tumblr] != 0 %>
      <%= render 'tumblrsearch' %>
    <% elsif params[:search_type] == 'all' %>
      <h4>Feed Results:</h4><br>
      <%= flash[:feed_notice] %><br><br>
      <%= render 'rssfeedsearch' if (@search[:feed] != 0 && @search[:feed] != 200) %>
      <h4>Tumblr Results:</h4><br>
      <%= flash[:tumblr_notice] %><br><br>
      <%= render 'tumblrsearch' if @search[:tumblr] != 0 %>
      <h4>Twitter Results:</h4><br>
      <%= render 'twittersearch' %>
    <% else %>
    <!-- This is where the actual posts go! -->
      <%= render 'posts' %>

  <% end %>
   </div>
</div>