config/routes.rb
Gobblr::Application.routes.draw do
  root 'welcome#index'

  post '/auth/:provider/callback' => 'sessions#create'
  get '/auth/:provider/callback'  => 'sessions#create' 
  get '/users/:id'                => 'users#show', as: :home
  post '/users/:id'               => 'feeds#create', as: :feeds
  get '/logout'                   => 'sessions#destroy', as: :logout
  get 'feeds/twitter_create'      => 'feeds#add_home_twitter_feed', as: :twitter_feed_create
  post '/posts/:id/favorite'      => "posts#fave", as: :favorite
  post '/posts/:id/unfavorite'    => "posts#unfave", as: :unfavorite
  post '/posts/:id/retweet'       => "posts#retweet", as: :retweet

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gobblr</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <span class="navbar-brand">
                  <% if @current_user %>
                    <%= link_to image_tag('hand.png', height: 45), home_path(@current_user.id) %>
                  <% else %>
                    <%= image_tag('hand.png', height: 45) %>
                  <% end %>
                  Gobblr</span>
            </div>
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <% if @current_user %>
                      <li>Add Accounts:<%= (link_to image_tag('twitter.png', height: '32'), '/auth/twitter') if @current_user.authorizations.where(provider: 'twitter').count != 1 %>
                      </li>
                      <li>
                        <%= (link_to image_tag('github.png', height: '32'), '/auth/github') if @current_user.authorizations.where(provider: 'github').count != 1 %>
                      </li>
                      <li>
                         <%= (link_to image_tag('facebook.png', height: '32'), '/auth/facebook') if @current_user.authorizations.where(provider: 'facebook').count != 1 %>
                      </li>
                      <li><%= link_to 'Sign Out', logout_path %>
                      </li>
                    <% end %>
                </ul>
            </div>
          </nav>

<div class='container'>
<%= yield %>
</div>
  <script>
    !function(d,s,id){
      var js,fjs=d.getElementsByTagName(s)[0];
      if(!d.getElementById(id)){
        js=d.createElement(s);
        js.id=id;
        js.src="https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js,fjs);
      }
    }(document,"script","twitter-wjs");
  </script>
</body>
</html>